In [174]:
import numpy as np
import cv2
import scipy.optimize as opt
np.set_printoptions(precision=None, suppress=True)

In [220]:
F = np.zeros((n_images,n_images,3,3))

In [9]:
def calc_fund_matrix(points1,points2):
    '''
    Takes in 2 arrays of matching points 
    Return Fundamental matrix computes 
    using 8 point algorithm
    '''
    F, mask = cv2.findFundamentalMat(points1,points2,cv2.FM_8POINT)
    return F 

In [106]:
def normalize_coordinates(p):
    # Normalization matrix
    T_m = normalization_matrix(p)
    # Normalized points
    p_norm = (T_m@(p.T)).T
    return p_norm, T_m

    
def manual_find_F_matrix(xy1,xy2):
    # Input: xy1 , xy2 - 2d array of points: row per point [x,y]
    # xy1 - for image 1, xy2 - for image 2
    # FM compute fundametal matrix from point correspondence
    #    at least 8 points are needed
    
    n_points = xy1.shape[0]
    if n_points < 8:
        print('8 points at least are needed')
    
    #add 3rd coordinate '1'
    xy1 = projectivation(xy1)
    xy2 = projectivation(xy2)
    
    
    #normalize coordinates
    xy1_norm, T1 = normalize_coordinates(xy1)
    xy2_norm, T2 = normalize_coordinates(xy2)
    
    # Preparing the equation matrix
    M = np.zeros((n_points,9))
    M[:,0] = xy1_norm[:,0]*xy2_norm[:,0] # x1 * x2
    M[:,1] = xy1_norm[:,0]*xy2_norm[:,1]# x1 * y2 
    M[:,2] = xy1_norm[:,0] # x1
    M[:,3] = xy1_norm[:,1]*xy2_norm[:,0] # y1 * x2
    M[:,4] = xy1_norm[:,1]*xy2_norm[:,1] # y1 * y2
    M[:,5] = xy1_norm[:,1] # y1
    M[:,6] = xy2_norm[:,0] # x2
    M[:,7] = xy2_norm[:,2] # y2
    M[:,8] = 1

    # calc M^T * M to get symmetruc square matrix
    W = M.T@M
    
    # desompose W into U (singular values), D (diagonal matrix), Vt (singular vectors)
    U,D,Vt = la.svd(W,compute_uv=True)
    a = U[:,-1]     # solution vector corresponding to the 
                    # least singular value
    A = np.reshape(a.T,(3,3))

    # Returning to non-normalized points
    F = la.inv(T2)@A@T1

    return F

In [97]:
### function used in class
def projectivation(p):
    '''
    Input: p, Nxd matrix = N points in R^d
    Output: q, Nx(d+1) = N points in P^d
    '''
    N,d = p.shape
    q = np.ones((N,d+1))
    q[:,0:d] = p 
    return q 

def affinization(q):
    '''
    Input: q, Nx(d+1) = N points in P^d
    Output: p, Nxd matrix = N points in R^d
    '''
    N,d1 = q.shape
    d = d1-1
    p = np.ones((N,d))
    p = q[:,0:d]/q[:,d:d+1] 
    
    return p

def normalization_matrix(p):
    '''
    Input: p: Nx2 matrix
    Output: T, normalization matrix (in projective plane) 
    '''

    # Computation
    m = np.mean(p,axis=0)
    q = p - np.repeat(m[np.newaxis,:],N,axis=0)
    w = np.sqrt(np.sum(q**2,axis=1))
    scale = 1/np.mean(w)

    # Normalization matrix
    T = np.zeros((3,3))
    T[2,2] = 1
    T[0,0] = scale
    T[0,2] = -m[0]*scale
    T[1,1] = scale
    T[1,2] = -m[1]*scale
        
    return T

In [221]:
def mendonca_cost_func(X):
    '''
    computes Mendonca & Cipolla Cost function to find the Optimal Intrinsic Parameters
    Input
    X      - Approximate Values of Intrinsics
    Output
    E    - Computed Cost
    '''

    #Transform Intrinsics to Matrix Form
    K = np.array([
        [X[0],X[1],X[2]],
        [0,X[3],X[4]],
        [0,0,1]
    ])
    #Initialize Cost
    E = 0
    print (type(E))
    # For the Denominator term of Mendonca & Cipolla's Equation
#        F      - globally defined Fundamental Matrix between given two Images

    N = len(F[0]);

    Den = N*(N-1)/2; # For N Images we can find N(N-1)/2 Fundamental Matrix

    #Compute the Cost using Mendonca & Cipolla's Equation
    for i in range(1,len(F[0]-1)):
        for j in range (i+1,len(F[0])):

            # Compute the Essential Matrix 'EM' from Fundamental of images i,j
            EM = K.T @ F[i,j,:,:] @ K

            # Compute SVD of Essential Matrix
            _,D,_ = np.linalg.svd(EM)
             # Singular Values (3rd value, D[3] is 0)
            r = D[0]
            s = D[1]

            #  Compute Cost

            E+= (1/Den) * (r - s)/s

    return E


In [235]:
#number of matching points
N = 30
n_images = 4
# original coordinates of points (x,y)
p = np.zeros((n_images,N,2))
# projective coordinats of points (x,y,1)
pj = np.zeros((n_images,N,3))

# randomly initialize 1st image (index #0)
p[0] = np.random.randint(0,500,(N,2))
pj[0] = projectivation(p[0])

#init random matrices to transform original image
A = np.random.randint(-5,5,(n_images-1,3,3))

# transform original image to get new images 
for i in range(1,n_images):
    pj[i] = (A[i-1]@pj[0].T).T
    p[i] = affinization(pj[i])
   
# insert noise
noise_level1 = 0.25
for i in range(n_images):
    p[i] += noise_level1*np.random.randn(N,2)

In [236]:
print (p.shape)

(4, 30, 2)


In [237]:
for i in range(n_images-1):
    for j in range(i+1,n_images):
        F[i,j] = calc_fund_matrix(p[i],p[j])
        print (F[i,j])



[[-0.030192    0.01530129 -0.38670543]
 [ 0.03427473 -0.02183841  0.46556299]
 [ 0.07900556 -0.03803518  1.        ]]
[[-0.01810595  0.0170373   0.51830345]
 [ 0.01162772 -0.00217544 -1.93817121]
 [ 0.02878683 -0.03704823  1.        ]]
[[-0.00949929 -0.01001102  6.64427855]
 [-0.01570198 -0.01123177  8.67418165]
 [-0.00553288  0.00077791  1.        ]]
[[-0.00375459  0.00503599  0.0068884 ]
 [-0.14007116  0.15177254  0.3405705 ]
 [-0.41140952  0.44591012  1.        ]]
[[-0.31250995  0.32801583  0.77443912]
 [-0.67842945  0.73595071  1.67731131]
 [-0.40551437  0.45553624  1.        ]]
[[0.01948706 1.11186429 3.25763178]
 [0.06250193 1.46983966 4.27816048]
 [0.04507264 0.35153929 1.        ]]


In [223]:
initial_K =  np.random.randint(-5,5,(5))

In [225]:
res = opt.minimize(mendonca_cost_func,x0=initial_K)

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class

In [238]:
print (res)

      fun: 2.7147020037840845
 hess_inv: array([[ 0.00150556,  0.00001416,  0.00005102, -0.00002267, -0.0000123 ],
       [ 0.00001416,  0.23213508,  0.06812753, -0.14406814, -0.03852093],
       [ 0.00005102,  0.06812753,  0.03278612, -0.04307501, -0.01886673],
       [-0.00002267, -0.14406814, -0.04307501,  0.08990718,  0.02413453],
       [-0.0000123 , -0.03852093, -0.01886673,  0.02413453,  0.01116051]])
      jac: array([ 0.00000069, -0.00000116, -0.00000393, -0.00000232, -0.00000697])
  message: 'Optimization terminated successfully.'
     nfev: 474
      nit: 63
     njev: 79
   status: 0
  success: True
        x: array([-0.00000001, -0.28272067, -0.18023026,  0.16179608,  0.95761203])


In [239]:
x = np.zeros((3,3))
x = [[res.x[0],res.x[1],res.x[2]],[0,res.x[3],res.x[4]],[0,0,1]]
print (np.matrix(x))

[[-0.00000001 -0.28272067 -0.18023026]
 [ 0.          0.16179608  0.95761203]
 [ 0.          0.          1.        ]]
