In [80]:
import pandas as pd
import os,sys, imp
sys.path.append('./src/')
import doc_utils_clean as doc_utils
import feature_utils
import defines
import numpy as np

In [81]:
doc_db =  pd.read_csv("./dataframes/doc_db.csv")
doc_db.sort_values(by='doc_idx_from_name',inplace=True)
doc_db

path                     file_name  \
3           ./tmp/01_aingimel3_lc.docx          01_aingimel3_lc.docx   
2          ./tmp/02_aingimel12_lc.docx         02_aingimel12_lc.docx   
1          ./tmp/03_aingimel26_lc.docx         03_aingimel26_lc.docx   
7                ./tmp/04_nun2_lc.docx               04_nun2_lc.docx   
5           ./tmp/05_kafhey_23_lc.docx          05_kafhey_23_lc.docx   
6          ./tmp/06_lamedbet21_lc.docx         06_lamedbet21_lc.docx   
0          ./tmp/07_alefsameh3_lc.docx         07_alefsameh3_lc.docx   
4         ./tmp/08_kafdalet_15_lc.docx        08_kafdalet_15_lc.docx   
35             tmp/09_kafhey_23_l.docx           09_kafhey_23_l.docx   
8          ./tmp/10_aingimel5_Mor.docx         10_aingimel5_Mor.docx   
9         ./tmp/11_aingimel10_Mor.docx        11_aingimel10_Mor.docx   
10        ./tmp/11_aingimel10_Mor.docx        11_aingimel10_Mor.docx   
11        ./tmp/12_aingimel16_Mor.docx        12_aingimel16_Mor.docx   
12        ./tmp/13_aingimel18_Mor.docx        13_aingimel18_Mor.docx   
13        ./tmp/14_aingimel22_Mor.docx        14_aingimel22_Mor.docx   
14        ./tmp/15_aingimel24_Mor.docx        15_aingimel24_Mor.docx   
15         ./tmp/16_aingimel7_Mor.docx         16_aingimel7_Mor.docx   
16  ./tmp/17_samehAleph16_DanaMor.docx  17_samehAleph16_DanaMor.docx   
17       ./tmp/18_kafTet7_DanaMor.docx       18_kafTet7_DanaMor.docx   
18      ./tmp/19_tsadek13_DanaMor.docx      19_tsadek13_DanaMor.docx   
19        ./tmp/20_kafDalet3_Dana.docx        20_kafDalet3_Dana.docx   
20          ./tmp/21_kafHey3_Dana.docx          21_kafHey3_Dana.docx   
21        ./tmp/22_kafDalet5_Dana.docx        22_kafDalet5_Dana.docx   
22        ./tmp/23_kafDalet7_Dana.docx        23_kafDalet7_Dana.docx   
23          ./tmp/24_kafHey5_Dana.docx          24_kafHey5_Dana.docx   
24        ./tmp/25_kafDalet9_Dana.docx        25_kafDalet9_Dana.docx   
25          ./tmp/26_kafHey9_Dana.docx          26_kafHey9_Dana.docx   
26       ./tmp/27_kafDalet11_Dana.docx       27_kafDalet11_Dana.docx   
27         ./tmp/28_kafHey11_Dana.docx         28_kafHey11_Dana.docx   
28         ./tmp/29_kafHey12_Dana.docx         29_kafHey12_Dana.docx   
29       ./tmp/30_kafDalet15_Dana.docx       30_kafDalet15_Dana.docx   
30         ./tmp/31_kafHey15_Dana.docx         31_kafHey15_Dana.docx   
31       ./tmp/32_kafDalet17_Dana.docx       32_kafDalet17_Dana.docx   
32         ./tmp/33_kafHey17_Dana.docx         33_kafHey17_Dana.docx   
33         ./tmp/34_kafHey18_Dana.docx         34_kafHey18_Dana.docx   
34         ./tmp/35_kafHey20_Dana.docx         35_kafHey20_Dana.docx   

    doc_idx_from_name  
3            1.000000  
2            2.000000  
1            3.000000  
7            4.000000  
5            5.000000  
6            6.000000  
0            7.000000  
4            8.000000  
35           9.000000  
8           10.000000  
9           11.000000  
10          11.000000  
11          12.000000  
12          13.000000  
13          14.000000  
14          15.000000  
15          16.000000  
16          17.000000  
17          18.000000  
18          19.000000  
19          20.000000  
20          21.000000  
21          22.000000  
22          23.000000  
23          24.000000  
24          25.000000  
25          26.000000  
26          27.000000  
27          28.000000  
28          29.000000  
29          30.000000  
30          31.000000  
31          32.000000  
32          33.000000  
33          34.000000  
34          35.000000

In [83]:
new_doc_idx = [9]
new_doc_idx.extend(np.arange(20,36))
new_doc_idx

[9, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

In [87]:
for idx in new_doc_idx:
    feature_utils.save_doc_features(idx)

9 sent lemma db saved
9 sent count db saved
9 sent features db saved
9 doc sent saved
9 sim_db sent saved
20 sent lemma db saved
20 sent count db saved
20 sent features db saved
20 doc sent saved
20 sim_db sent saved
21 sent lemma db saved
21 sent count db saved
21 sent features db saved
21 doc sent saved
21 sim_db sent saved
22 sent lemma db saved
22 sent count db saved
22 sent features db saved
22 doc sent saved
22 sim_db sent saved
23 sent lemma db saved
23 sent count db saved
23 sent features db saved
23 doc sent saved
23 sim_db sent saved
24 sent lemma db saved
24 sent count db saved
24 sent features db saved
24 doc sent saved
24 sim_db sent saved
25 sent lemma db saved
25 sent count db saved
25 sent features db saved
25 doc sent saved
25 sim_db sent saved
26 sent lemma db saved
26 sent count db saved
26 sent features db saved
26 doc sent saved
26 sim_db sent saved
27 sent lemma db saved
27 sent count db saved
27 sent features db saved
27 doc sent saved
27 sim_db sent saved
28 sen

In [88]:
imp.reload(feature_utils)
feature_utils.tfidf_build_all_save_per_doc(per_word=False)

TfIdf 4 saved
TfIdf 11 saved
TfIdf 30 saved
TfIdf 25 saved
TfIdf 9 saved
TfIdf 23 saved
TfIdf 2 saved
TfIdf 17 saved
TfIdf 28 saved
TfIdf 31 saved
TfIdf 24 saved
TfIdf 5 saved
TfIdf 10 saved
TfIdf 29 saved
TfIdf 3 saved
TfIdf 16 saved
TfIdf 22 saved
TfIdf 8 saved
TfIdf 27 saved
TfIdf 32 saved
TfIdf 18 saved
TfIdf 6 saved
TfIdf 15 saved
TfIdf 21 saved
TfIdf 34 saved
TfIdf 12 saved
TfIdf 7 saved
TfIdf 19 saved
TfIdf 26 saved
TfIdf 33 saved
TfIdf 20 saved
TfIdf 35 saved
TfIdf 14 saved
TfIdf 1 saved


In [89]:
# imp.reload(feature_utils)#
feature_utils.tfidf_build_all_save_per_doc(per_word=True)

TfIdf 4 saved
TfIdf 11 saved
TfIdf 30 saved
TfIdf 25 saved
TfIdf 9 saved
TfIdf 23 saved
TfIdf 2 saved
TfIdf 17 saved
TfIdf 28 saved
TfIdf 31 saved
TfIdf 24 saved
TfIdf 5 saved
TfIdf 10 saved
TfIdf 29 saved
TfIdf 3 saved
TfIdf 16 saved
TfIdf 22 saved
TfIdf 8 saved
TfIdf 27 saved
TfIdf 32 saved
TfIdf 18 saved
TfIdf 6 saved
TfIdf 15 saved
TfIdf 21 saved
TfIdf 34 saved
TfIdf 12 saved
TfIdf 7 saved
TfIdf 19 saved
TfIdf 26 saved
TfIdf 33 saved
TfIdf 20 saved
TfIdf 35 saved
TfIdf 14 saved
TfIdf 1 saved


### Run cross-validation on 35 files

In [49]:
from operator import itemgetter
def get_prediction(train_idx,test_idx,X,y):
    crf = CRF(
    min_freq = 5,
    algorithm='lbfgs',
    c1=0.1,
    c2=0.1,
    max_iterations=100,
    all_possible_transitions=True,
    )
#     print ("Test idx: {}..., train idx: {}...".format(train_idx[:10],test_idx[:10]))
    X_train = itemgetter(*train_idx)(X)
    y_train  = itemgetter(*train_idx)(y)
    X_test = itemgetter(*test_idx)(X)
    y_test = itemgetter(*test_idx)(y)
    crf.fit(X_train, y_train)
    y_pred  =  crf.predict(X_test)
    labels = list(crf.classes_)
    f1 = metrics.flat_f1_score(y_test, y_pred,average='weighted', labels=labels)
    recall = metrics.flat_recall_score(y_test, y_pred,average='weighted', labels=labels)
    precision = metrics.flat_precision_score(y_test, y_pred,average='weighted', labels=labels)
    return [f1,recall,precision]

In [50]:
def leaveOneOut_validate(X,y,groups,seq_len,step):
    logo = LeaveOneGroupOut()
    score_list = []
    for train_idx, test_idx in logo.split(X, y, groups):
        score_list.append(get_prediction(train_idx,test_idx,X,y))
    return np.array(score_list)

In [122]:
from sklearn_crfsuite import scorers, CRF
from sklearn_crfsuite import metrics
from sklearn_crfsuite.metrics import flat_classification_report
from sklearn.model_selection import LeaveOneGroupOut,LeavePGroupsOut


In [91]:
score_db = pd.DataFrame()


In [92]:
def add_score_to_db(score_db,prefix,score):
    mean_values = score.mean(axis=0)
    print("mean_values {}".format(mean_values))
    score_db.loc[prefix,"f1"] = mean_values[0]
    score_db.loc[prefix,"recall"] = mean_values[1]
    score_db.loc[prefix,"precision"] = mean_values[2]
    return score_db

### Pack features per doc: with TfIDF chars, with only features that hold no zero

In [98]:
imp.reload(feature_utils)
X,y,group =  feature_utils.pack_all_doc_sentences()

4 doc 543 sentences packed
Doc 4 sentenced packed
11 doc 174 sentences packed
Doc 11 sentenced packed
30 doc 258 sentences packed
Doc 30 sentenced packed
25 doc 331 sentences packed
Doc 25 sentenced packed
9 doc 384 sentences packed
Doc 9 sentenced packed
23 doc 237 sentences packed
Doc 23 sentenced packed
2 doc 186 sentences packed
Doc 2 sentenced packed
17 doc 622 sentences packed
Doc 17 sentenced packed
28 doc 445 sentences packed
Doc 28 sentenced packed
31 doc 283 sentences packed
Doc 31 sentenced packed
24 doc 613 sentences packed
Doc 24 sentenced packed
5 doc 375 sentences packed
Doc 5 sentenced packed
10 doc 424 sentences packed
Doc 10 sentenced packed
29 doc 398 sentences packed
Doc 29 sentenced packed
3 doc 152 sentences packed
Doc 3 sentenced packed
16 doc 438 sentences packed
Doc 16 sentenced packed
22 doc 284 sentences packed
Doc 22 sentenced packed
8 doc 259 sentences packed
Doc 8 sentenced packed
27 doc 217 sentences packed
Doc 27 sentenced packed
32 doc 253 sentences pac

### Check feature set

In [102]:
X[19]

{'is_client': 1,
 'sent_len': 76.0,
 'TOKEN': 17,
 'POSTAG_AT': 1,
 'POSTAG_CONJ': 5,
 'POSTAG_COP': 1,
 'POSTAG_DEF': 4,
 'POSTAG_DTT': 1,
 'POSTAG_IN': 2,
 'POSTAG_INTJ': 2,
 'POSTAG_NN': 6,
 'POSTAG_NNP': 2,
 'POSTAG_PREPOSITION': 2,
 'POSTAG_VB': 2,
 'f_gen_M': 11,
 'f_num_P': 2,
 'f_num_S': 9,
 'f_per_1': 2,
 'f_per_3': 1,
 'f_tense_PAST': 2,
 '-1:is_client': 1,
 '-1:sent_len': 52.0,
 '-1:TOKEN': 11,
 '-1:POSTAG_IN': 1,
 '-1:POSTAG_INTJ': 1,
 '-1:POSTAG_NN': 2,
 '-1:POSTAG_NNP': 1,
 '-1:POSTAG_PREPOSITION': 1,
 '-1:POSTAG_PRP': 1,
 '-1:POSTAG_RB': 2,
 '-1:POSTAG_S_PRN': 1,
 '-1:POSTAG_TEMP': 1,
 '-1:POSTAG_VB': 3,
 '-1:f_gen_M': 7,
 '-1:f_num_P': 1,
 '-1:f_num_S': 6,
 '-1:f_per_1': 2,
 '-1:f_per_3': 2,
 '-1:f_tense_PAST': 2,
 '-2:is_client': 1,
 '-2:sent_len': 48.0,
 '-2:TOKEN': 10,
 '-2:POSTAG_BN': 1,
 '-2:POSTAG_IN': 1,
 '-2:POSTAG_INTJ': 2,
 '-2:POSTAG_JJ': 2,
 '-2:POSTAG_NN': 2,
 '-2:POSTAG_PRP': 1,
 '-2:POSTAG_VB': 1,
 '-2:f_gen_M': 7,
 '-2:f_num_P': 2,
 '-2:f_num_S': 5,
 '-2

In [105]:
imp.reload(feature_utils)
shapes = [(6,6),(6,3),(6,1)]
score_db = pd.DataFrame()
for shape in shapes:
    seq_len = shape[0]
    step = shape[1]
    X_shaped,y_shaped,groups_shaped = feature_utils.reshape_doc_features_to_sequence(X,y,group,seq_len,step)
    score = leaveOneOut_validate(X_shaped,y_shaped,groups_shaped,seq_len,step)
    add_score_to_db(score_db,"{}_{}".format(seq_len,step),score)

doc sentences reshaped: from 11733 to 1956
mean_values [0.76735651 0.76704826 0.79595948]
doc sentences reshaped: from 11733 to 3911
mean_values [0.75805815 0.75864557 0.78100446]
doc sentences reshaped: from 11733 to 11733
mean_values [0.76324848 0.76188583 0.78334989]


In [106]:
score_db

f1   recall  precision
6_6 0.767357 0.767048   0.795959
6_3 0.758058 0.758646   0.781004
6_1 0.763248 0.761886   0.783350

### Run example on 35 files, with TfIDF chars, with only features that hold no zero

In [124]:
crf = CRF(
    min_freq = 5,
    algorithm='lbfgs',
    c1=0.1,
    c2=0.1,
    max_iterations=100,
    all_possible_transitions=True,
    )
X_shaped,y_shaped,groups_shaped = feature_utils.reshape_doc_features_to_sequence(X,y,group,6,6)
group_indices = set(group)
print(len(group_indices),group_indices)
num_test_doc = int(len(group_indices)*0.15)
logo =  LeavePGroupsOut(n_groups=num_test_doc)
split = logo.split(X_shaped, y_shaped, groups_shaped)
itteration = 0
for train_idx, test_idx in split:
    if(itteration > 2):
        break
    itteration +=1
print(train_idx[:10],test_idx[:10])
print(len(train_idx),len(test_idx))
X_train = itemgetter(*train_idx)(X_shaped)
y_train  = itemgetter(*train_idx)(y_shaped)
X_test = itemgetter(*test_idx)(X_shaped)
y_test = itemgetter(*test_idx)(y_shaped)
crf.fit(X_train, y_train)
y_pred  =  crf.predict(X_test)
labels = list(crf.classes_)
f1 = metrics.flat_f1_score(y_test, y_pred,average='weighted', labels=labels)
recall = metrics.flat_recall_score(y_test, y_pred,average='weighted', labels=labels)
precision = metrics.flat_precision_score(y_test, y_pred,average='weighted', labels=labels)
print ("f1 {}\nrecall {}\nprecition {}".format(f1,recall,precision))

doc sentences reshaped: from 11733 to 1956
34 {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35}
[ 91  92  93  94  95  96  97  98  99 100] [0 1 2 3 4 5 6 7 8 9]
1662 294
f1 0.7697249894898157
recall 0.771152754116979
precition 0.7685780508296276


## Run on docs [1-19] ( except 13 and 9 )

In [378]:
imp.reload(feature_utils)
X,y,group =  feature_utils.pack_all_doc_sentences()

4 doc 543 sentences packed
11 doc 174 sentences packed
2 doc 186 sentences packed
17 doc 622 sentences packed
5 doc 375 sentences packed
10 doc 424 sentences packed
3 doc 152 sentences packed
16 doc 438 sentences packed
8 doc 259 sentences packed
18 doc 157 sentences packed
6 doc 471 sentences packed
15 doc 159 sentences packed
12 doc 198 sentences packed
7 doc 448 sentences packed
19 doc 374 sentences packed
14 doc 176 sentences packed
1 doc 618 sentences packed
5774 sentenced packed for 17 docs


In [380]:
imp.reload(feature_utils)

seq_len = 6
step = 6
X_shaped,y_shaped,groups_shaped = feature_utils.reshape_doc_features_to_sequence(X,y,group,seq_len,step)
score = leaveOneOut_validate(X_shaped,y_shaped,groups_shaped,seq_len,step)
add_score_to_db("{}_{}".format(seq_len,step),score)

4 doc sentences reshaped: from 5774 to 963
score [[0.74161977 0.74267101 0.7415918 ]
 [0.8380273  0.77419355 0.9601518 ]
 [0.83343915 0.78666667 0.91792075]
 [0.74374676 0.73809524 0.76641828]
 [0.74424675 0.74462366 0.74439964]
 [0.83397289 0.84177215 0.83160188]
 [0.68858844 0.69333333 0.69302711]
 [0.81784944 0.81395349 0.82345741]
 [0.82830498 0.83333333 0.8265873 ]
 [0.77465006 0.77011494 0.78001768]
 [0.7290769  0.74747475 0.71851852]
 [0.82272137 0.85555556 0.84836601]
 [0.88601975 0.81410256 0.97187438]
 [0.78109981 0.78310502 0.7815498 ]
 [0.43676666 0.41666667 0.73547893]
 [0.64686754 0.68589744 0.67503621]
 [0.90586739 0.89247312 0.93068141]]


In [381]:
score_db

f1   recall  precision
6_6 0.767816 0.760825   0.808628
6_3 0.754951 0.747010   0.790973
6_1 0.760612 0.755090   0.786439

## Run on docs [1-19] with TfIdf per char

In [44]:
imp.reload(feature_utils)
X,y,group =  feature_utils.pack_all_doc_sentences()

4 doc 543 sentences packed
11 doc 174 sentences packed
2 doc 186 sentences packed
17 doc 622 sentences packed
5 doc 375 sentences packed
10 doc 424 sentences packed
3 doc 152 sentences packed
16 doc 438 sentences packed
8 doc 259 sentences packed
18 doc 157 sentences packed
6 doc 471 sentences packed
15 doc 159 sentences packed
12 doc 198 sentences packed
7 doc 448 sentences packed
19 doc 374 sentences packed
14 doc 176 sentences packed
1 doc 618 sentences packed
5774 sentenced packed for 17 docs


### Cross - validate

In [56]:
tf_char_score_db = pd.DataFrame()
seq_len = 6
step = 6
X_shaped,y_shaped,groups_shaped = feature_utils.reshape_doc_features_to_sequence(X,y,group,seq_len,step)
score = leaveOneOut_validate(X_shaped,y_shaped,groups_shaped,seq_len,step)
add_score_to_db(tf_char_score_db,"{}_{}".format(seq_len,step),score)

4 doc sentences reshaped: from 5774 to 963
mean_values [0.7742163  0.76612805 0.81464162]


f1   recall  precision
6_6 0.774216 0.766128   0.814642

### Run example

In [75]:
crf = CRF(
    min_freq = 5,
    algorithm='lbfgs',
    c1=0.1,
    c2=0.1,
    max_iterations=100,
    all_possible_transitions=True,
    )
logo = LeaveOneGroupOut()
split = logo.split(X_shaped, y_shaped, groups_shaped)
itteration = 0
for train_idx, test_idx in split:
    if(itteration > 1):
        break
    itteration +=1
print(train_idx[:10],test_idx[:10])
print(len(train_idx),len(test_idx))
X_train = itemgetter(*train_idx)(X_shaped)
y_train  = itemgetter(*train_idx)(y_shaped)
X_test = itemgetter(*test_idx)(X_shaped)
y_test = itemgetter(*test_idx)(y_shaped)
crf.fit(X_train, y_train)
y_pred  =  crf.predict(X_test)
labels = list(crf.classes_)
f1 = metrics.flat_f1_score(y_test, y_pred,average='weighted', labels=labels)
recall = metrics.flat_recall_score(y_test, y_pred,average='weighted', labels=labels)
precision = metrics.flat_precision_score(y_test, y_pred,average='weighted', labels=labels)
print ("f1 {}\nrecall {}\nprecition {}".format(f1,recall,precision))

[0 1 2 3 4 5 6 7 8 9] [388 389 390 391 392 393 394 395 396 397]
938 25
f1 0.8896014709997201, recall 0.8733333333333333, precition 0.9130256410256411


In [79]:
imp.reload(feature_utils)
feature_utils.get_prediction_report(y_test,y_pred)

AttributeError: type object 'ConfusionMatrixDisplay' has no attribute 'from_predictions'